import type { Metadata } from 'next'
import './globals.scss'

import Providers from '@/providers'
import ConditionalLayout from '@/components/ConditionalLayout'
import getCurrentUser from '@/actions/getCurrentUser'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <Providers>
          <ConditionalLayout currentUser={currentUser}>
            {children}
          </ConditionalLayout>
        </Providers>
      </body>
    </html>
  )
}
