import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'

import Providers from '@/providers'
import Navbar from '@/layouts/navbar/Navbar'
import getCurrentUser from '@/actions/getCurrentUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar currentUser={currentUser} />
          {children}
        </Providers>
      </body>
    </html>
  )
}
